rankine.o: rankine.cpp /Cantera1.8-Radcal/build/include/cantera/Cantera.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ct_defs.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/config.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/../config.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/global.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ct_defs.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ctexceptions.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/logger.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/clockWC.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/xml.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ctexceptions.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/global.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/stringUtils.h \
 /Cantera1.8-Radcal/build/include/cantera/PureFluid.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/PureFluidPhase.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ThermoPhase.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/Phase.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/State.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/utilities.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/Constituents.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/SpeciesThermo.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/stringUtils.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/xml.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/Elements.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/vec_functions.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ctml.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/Array.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/mix_defs.h \
 /Cantera1.8-Radcal/build/include/cantera/kinetics.h \
 /Cantera1.8-Radcal/build/include/cantera/thermo.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ThermoFactory.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/FactoryBase.h \
 /Cantera1.8-Radcal/build/include/cantera/importPhase.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ThermoPhase.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/SurfPhase.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/EdgePhase.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/SurfPhase.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/Kinetics.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/InterfaceKinetics.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/Kinetics.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/RateCoeffMgr.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/RxnRates.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/reaction_defs.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ReactionStoichMgr.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/GasKinetics.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/ThirdBodyMgr.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/Enhanced3BConc.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/FalloffMgr.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/FalloffFactory.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/KineticsFactory.h \
 /Cantera1.8-Radcal/build/include/cantera/kernel/importKinetics.h
